### ISSUE TITLE
No instance updates since Jan 12

### ISSUE THREAD

**Issue by mszell** [TheKinrar/instances#144]
Hi, it seems that there has been no data update since Jan 12. As a consequence also dependent services/sites such as https://observablehq.com/@mauforonda/what-goes-on-in-mastodon got stuck on Jan 12. Not sure what happened - just posting here in case you were not aware. Thanks for the great site!

**Comment by mauforonda** [comment]
Hi, apparently instances.social isn't fetching or reporting fresh data as often as it used to. This is plot of the last update time for every instance at `2023-01-20T00:53:31+00:00`:

![image](https://user-images.githubusercontent.com/4010711/213600054-a7587c66-be6a-4c9e-abc3-9a34194c131e.png)

As you can see, data from most instances was retrieved more than a day ago. 

In the repo at [mauforonda/mastodon_timeline/](https://github.com/mauforonda/mastodon_timeline/), where I aggregate these data for the [observable notebook](https://observablehq.com/@mauforonda/what-goes-on-in-mastodon), I was filtering out data older than 3 hours ago. It seemed the most reasonable decision, but since January 12 it looks very empty and wrong. So I'm temporarily [letting older data in](https://github.com/mauforonda/mastodon_timeline/commit/b98f3d585eb75d4c4dbdb1819c9030c52cf78769) until things improve at the source. That should make the plots in the notebook look better, though a bit misleading, for a while.

Hopefully this gets resolved soon.

**Comment by drumpat01** [comment]
Ah I was wondering why I added my instance (thetaoist.social) and had not seen it appear in the list since I added it after the 12th. Hopefully this gets resolved soon.

**Comment by mauforonda** [comment]
The stituation began to improve in the past few hours. I'll be tracking how fresh are the instances.social records every ~3 hours at https://observablehq.com/@mauforonda/fresh-instances
![Screenshot 2023-01-21 at 17-13-51 Fresh instances _ Mauricio Foronda Observable](https://user-images.githubusercontent.com/4010711/213887432-5252b474-2c44-4a21-8dfc-b6482aefff02.png)

**Comment by TheKinrar** [comment]
Was fixed yesterday indeed. The probe got a bit overloaded. Thanks for the report!

**Comment by mauforonda** [comment]
Thank you for keeping this project alive :)

**Comment by TheKinrar** [comment]
Had another server issue, fixed once again. Thanks for reporting. In the future, please open a new issue: I did not see your reply here. :)

**Comment by mauforonda** [comment]
Will do. Thank you :)
